gRPC fails to build on gcc-8
Due to new warnings in gcc-8, sysdig fails to build on e.g. Fedora 28:

```
src/core/ext/transport/chttp2/transport/flow_control.cc: In member function 'uint32_t grpc_core::chttp2::TransportFlowControl::MaybeSendUpdate(bool)':
src/core/ext/transport/chttp2/transport/flow_control.cc:170:74: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
   const uint32_t target_announced_window = (const uint32_t)target_window();
```

gRPC uses hardcoded -Werror which isn't really the best idea ever so let's patch it out