userspace/sinspui: always use "%s"-style format for printf()-style functions (#1810)
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    sysdig/userspace/sinspui/cursescomponents.cpp: In member function 'void curses_textbox::print_no_data()':
    sysdig/userspace/sinspui/cursescomponents.cpp:878:15: error: format not a string literal and no format arguments [-Werror=format-security]
      878 |   wstr.c_str());
          |               ^

Let's wrap all the missing places with "%s" format.

sysdig-CLA-1.0-signed-off-by: Sergei Trofimovich <slyich@gmail.com>
Signed-off-by: Sergei Trofimovich <slyich@gmail.com>