Merging to falco-master for 0.5.0 (#702)
* K8s fixes + max & windows build (#666)

* mac build (not tested)

* linux build and run

* Done
- add blocking connect/init mode to k8s
- sysdig connect and init are blocking now (faster startup)
- move k8s http to 1.1 to utilize keepalive
- fixed chunk purging bug
- reuse state socket for watch (no diconnect after state fetch)
Todo
- improve handler receive error handling
- test https
- blocking resolve

* watch redirection fix

* fix watch transition; detect http 1.1 watch emission end and reconnect promptly; fix jq filter order bug

* fix mac build

* fix linux compile error; add docker flag to handler

* windows build

* fix race condition when no data on first attempt; make k8s default http 1.1

* fix blocking read

* Add less to docker image

* Added s390x support to sysdig source (#667)

* Update ppm.h

Added support for s390x

* Update ppm.h

re committing changes related to s390x

* Revert "Added s390x support to sysdig source (#667)"

This reverts commit bf7ae5a02457f3ebe25e9b76054b47267458771f.

* Added s390 support to sysdig source (#671)

* Update ppm.h

Added support for s390x

* Update ppm.h

re committing changes related to s390x

* build: Fix openssl build when not using the bundled library. (#672)

Otherwise, with
cmake -DCMAKE_BUILD_TYPE=Debug  -DUSE_BUNDLED_OPENSSL=OFF ..
one gets

```
[ 96%] Linking CXX executable csysdig
[ 97%] Linking CXX executable sysdig
/usr/bin/ld: ../libsinsp/libsinsp.a(k8s_handler.cpp.o): undefined reference to symbol 'SSL_CTX_use_PrivateKey_file'
/usr/lib/libssl.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [userspace/sysdig/CMakeFiles/csysdig.dir/build.make:131: userspace/sysdig/csysdig] Error 1
make[1]: *** [CMakeFiles/Makefile2:275: userspace/sysdig/CMakeFiles/csysdig.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../libsinsp/libsinsp.a(k8s_handler.cpp.o): undefined reference to symbol 'SSL_CTX_use_PrivateKey_file'
/usr/lib/libssl.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [userspace/sysdig/CMakeFiles/sysdig.dir/build.make:129: userspace/sysdig/sysdig] Error 1
make[1]: *** [CMakeFiles/Makefile2:323: userspace/sysdig/CMakeFiles/sysdig.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

This is because linking to libssl and libcrypto is not done (after
find_package in CMakeLists.txt) when using
the system libraries.

Also, fix the curl ssl dependency.

sysdig-CLA-1.0-signed-off-by: Raghavendra Prabhu <me@rdprabhu.com>

* - keep single k8s socket opened throughout session
- fix transition from non-chunked to chunked k8s handler
- change active k8s handler filter from reference to pointer
- remove unnecessary socket handler docker flag
- early terminate k8s blocking request loop on JSON end detect
- increase k8s blocking loop sleep to 10ms
- fix some logs

* missing deployments fix

* fix, part II; Missing k8s metadata #251

* make iolen signed

* fix code formatting

* fix (un)signed warnings; lower k8s handler creation log severity to debug

* replace http parser

* Changes for s390 , removed unsupported syscalls (#676)

added checks for unused macros on s390x
sysdig-CLA-1.0-signed-off-by: Ketan Kunde ketan22584@gmail.com

* Parse Conf from Docker

* Detect/remove stale threadinfo in clone children

When parsing clone exit events, specifically for the child half of a
clone and when in a container, detect and potentially remove stale
threadinfo state for the child thread.

Generally the client have of a clone is responsible for creating the
thread state for the new thread, as long as the parent is in a
container. See the parent half of the "if(childtid == 0)" statement. We
simply need to verify in the child half that the parent really was in a
container.

You can find the parent thread id from the syscall return information,
which is moved up from below. Look up the parent thread and see if its
vtid/vpid differs from tid/pid. If so, any existing thread state must be
stale and remove it. Note that you can't use
evt->m_tinfo->get_parent_thread() directly, as that comes from the
existing potentially stale threadinfo.

This fixes https://github.com/draios/sysdig/issues/664.

* Remove cwd parsing from the driver because the function became sleepable in 4.8 (https://github.com/torvalds/linux/commit/47be61845c775643f1aa4d2a54343549f943c94c).

When forking a new process, inherit the cwd from the parent.

* Use main_thread for set_cwd/get_cwd

* Mesos token auth (#673)

Support DC/OS token auth and HTTPS on Mesos

* Remove spurious code

* Probe builder with timeout (#683)

* add timeout to urlopen operations

* add timeout to download operations

* retry download max 10 times

* exlude 4.9 from ubuntu repos (#685)

* add msg end handler

* sysdig with https k8s-api failed #687

* windows compile errors

* return an exception when a filter only fiels is used for display

* bugfix: evtin.span.*.tags filter fields were not working properly

* evtin* fields can also be used as display fields now

* minor cleanup

* add stopwatch utility

* Fix compilation issues with kernel 4.9 (#684)

* Fix compilation issues with kernel 4.9

related commits:
https://github.com/torvalds/linux/commit/4c737b41de7f4eef2a593803bad1b918dd718b10
https://github.com/torvalds/linux/commit/b9d989c7218ac922185d82ad46f3e58b27a4bea9

* map io cgroup to blkio, fix for kernels >= 4.8

* Fix tracer code errors

* Fix ipv4 mapped ipv6 when used on sendto and receiver endpoint is 0

* Use https for all downloads.

Use https instead of http for all downloads within the install
script. In cases where the links refer to artifacts in our s3 bucket,
switch to https + s3.amazon.aws.com, which is already used by other urls
in the script.

This fixes https://github.com/draios/falco/issues/152.

* Fix format memory leak (#694)

* Whitespace diffs.

Committing separate from other changes.

* Fix leak when fmt string ends with non-filtercheck

Make sure that any final rawstring_check added to the list of tokens is
also added to m_chks_to_free, so it is properly freed.

This fixes https://github.com/draios/sysdig/issues/693.

* Clean up utils header file to be self-contained (#696)

Currently, utils.h has a lot of implicit dependencies on other stl
header files as well as assuming the std namespace is available.

Clean it up so it can be included on its own (say, in
https://github.com/draios/falco/pull/162).

* Fix typo in csysdig threads view

* a bit of work on the flame chisel

* support reading merged files

* wrong return value

* throttle k8s (#699)

* throttle max bytes per socket/cycle to 512k, max msgs for critical k8s entities to 100

* ifdef k8s caching

* adjust some commented (TBD) code

* fix the message limit logic

* osx build

* windows build, remove some warnings

* Revert "exlude 4.9 from ubuntu repos (#685)"

This reverts commit c183a573373b2d07a2919a05c8051dbe10941330.

* Reset marathon group json together with marathon app one (#700)

* Reset marathon group json together with marathon app one

* Remove spurious app_it declaration