Fix: get_buf_pointers() declaration should be static on non-windows platform
When compiling sysdig with Clang, one might run into this error:

Linking CXX executable sysdig
../libscap/libscap.a(scap.c.o): In function `scap_readbuf':
/home/travis/build/cbab/sysdig/userspace/libscap/scap.c:488: undefined reference to `get_buf_pointers'
/home/travis/build/cbab/sysdig/userspace/libscap/scap.c:506: undefined reference to `get_buf_pointers'
../libscap/libscap.a(scap.c.o): In function `check_scap_next_wait':
/home/travis/build/cbab/sysdig/userspace/libscap/scap.c:565: undefined reference to `get_buf_pointers'
collect2: ld returned 1 exit status
make[2]: *** [userspace/sysdig/sysdig] Error 1
make[1]: *** [userspace/sysdig/CMakeFiles/sysdig.dir/all] Error 2
make: *** [all] Error 2

This can be explained by the semantic difference of the "inline" keyword
with GCC compilers vs. Clang [1]. The fix is to add the static keyword,
since this function is only used in this compile unit.

[1] - http://clang.llvm.org/compatibility.html#inline

Signed-off-by: Christian Babeux <christian.babeux@0x80.ca>